trigger: none
pool: selfhostedagent
stages:
    - stage: nodejsinstall
      displayName: installnodejs
      jobs:
      - job: installjs
        displayName: installjs
        steps: 
        - task: UseNode@1
          inputs:
            checkLatest: true
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(Build.SourcesDirectory)'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/streamflix-app.zip'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

    - stage: DeployStage
      displayName: DeployStage
      dependsOn: nodejsinstall
      jobs:
        - job: DeployStage
          displayName: DeployStage
          steps: 
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(Pipeline.Workspace)/drop'
          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(7617312b-3d00-4f61-9fd7-4380615857ab)'
              appType: 'webAppLinux'
              WebAppName: 'streamflix-app-ajit'
              packageForLinux: '$(Pipeline.Workspace)/drop/streamflix-app.zip'
              DeploymentTypeLinux: 'oneDeploy'
